### ISSUE TITLE
Return of the `Invalid argument supplied for foreach()` error

### ISSUE THREAD

**Issue by davidlowryduda** [andrewbartel/Disqus_Recent_Comments#10]
I've just set up disqus and disqus_recent_comments on my personal site [davidlowryduda.com](davidlowryduda.com). You can see the displayed error message in the top right of the landing page.

The error itself refers to

```
Warning: Invalid argument supplied for foreach() 
in /home/djlowry/webapps/dldwordpress/wp-content/plugins/disqus-recent-comments-widget/disqus_recent_comments_widget.php on line 368
```

which is the same foreach() that pops up all the time. I cannot imagine that I'm the only one affected, so I've very likely done something wrong.

I should also mention that the support site [http://deusmachine.com/disqus-instructions.php](http://deusmachine.com/disqus-instructions.php) seems to lead to an empty page.

**Comment by davidlowryduda** [comment]
Oh - I'm tremendously sorry. It would help if I entered in my own shortname with correct spelling. I feel very silly.

So... no problem on that. (But the support link at deusmachine.com is still dead)

**Comment by andrewbartel** [comment]
Thanks @davidlowryduda , Deus is the company I used to work for when I made the plugin, it looks like they redid their site and didn't add the new install instructions, I'll get in touch with them, thanks for the heads up.
